version: '3'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - neo4j_data:/data
      - ./neo4j-community-x.x.x/conf:/conf
      - ./neo4j-community-x.x.x/plugins:/plugins
      - ./neo4j-community-x.x.x/import:/import
    environment:
      NEO4J_AUTH: neo4j/MyStrongPassword
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - public
volumes:
  neo4j_data:

networks:
  public:
